export const TOY_PARK_TRACK_WIDTH_SCALE = 0.42;

export const TOY_PARK_TRACK_TILE_LIBRARY = {
  start: {
    key: 'toy-park-start-board',
    label: '開始板塊',
    role: 'start',
    status: 'existing-flat-start-board-module',
  },
  straight: {
    key: 'toy-park-straight-road-tile',
    label: '直路板塊',
    role: 'straight',
    length: 14,
    prototypeLoopLength: 7,
    turnDegrees: 0,
    surfaceMarker: 'soft-blue-center-inset',
  },
  rampUp: {
    key: 'toy-park-ramp-up-road-tile',
    label: '上斜橋板塊（已取消）',
    role: 'disabled-ramp-up',
    length: 6.5,
    turnDegrees: 0,
    elevationRole: null,
    bridgeHeight: 0,
    surfaceMarker: null,
    disabled: true,
    status: 'cancelled-by-user-request-generator-uses-road-footprint-avoidance-instead-of-ramp-bridge',
  },
  elevatedStraight: {
    key: 'toy-park-elevated-straight-road-tile',
    label: '高架直路板塊（已取消）',
    role: 'disabled-elevated-straight',
    length: 7,
    turnDegrees: 0,
    elevationRole: null,
    bridgeHeight: 0,
    surfaceMarker: null,
    disabled: true,
    status: 'cancelled-by-user-request-generator-uses-road-footprint-avoidance-instead-of-elevated-bridge',
  },
  rampDown: {
    key: 'toy-park-ramp-down-road-tile',
    label: '落斜橋板塊（已取消）',
    role: 'disabled-ramp-down',
    length: 6.5,
    turnDegrees: 0,
    elevationRole: null,
    bridgeHeight: 0,
    surfaceMarker: null,
    disabled: true,
    status: 'cancelled-by-user-request-generator-uses-road-footprint-avoidance-instead-of-ramp-bridge',
  },
  variableBend: {
    key: 'toy-park-variable-angle-bend-tile',
    label: '可變角度彎位板塊',
    role: 'corner',
    length: 11,
    prototypeLoopLength: 4,
    defaultTurnDegrees: 60,
    minTurnDegrees: 15,
    maxTurnDegrees: 120,
    angleVariable: true,
    surfaceMarker: 'warm-yellow-variable-bend-inset',
  },
  disabledUTurn180: {
    key: 'toy-park-180-degree-u-turn-tile',
    label: '180度U-turn板塊（已取消）',
    role: 'disabled-u-turn',
    disabled: true,
    turnDegrees: 180,
    status: 'cancelled-by-user-request-u-turn-tile-looked-strange',
  },
  disabledCorner45: {
    key: 'toy-park-45-degree-bend-tile',
    label: '45度彎位板塊（已取消）',
    role: 'disabled-corner',
    disabled: true,
    replacedBy: ['toy-park-variable-angle-bend-tile'],
    status: 'cancelled-by-user-request',
  },
  finish: {
    key: 'toy-park-finish-board',
    label: '終點板塊',
    role: 'finish',
    length: 4.8,
    status: 'new-flat-finish-board-module',
  },
};


export const TOY_PARK_START_GATE_OVERRIDES = {
  style: 'track-aligned-gravity-staging-chute-with-optional-toy-park-racing-grid-start',
  gateEnabled: true,
  toyParkGateEnabled: false,
  racingGridStartEnabled: true,
  racingGridColumns: 4,
  racingGridOccupiedPerRow: 2,
  racingGridRows: 4,
  racingGridColumnSpacing: 2.34,
  racingGridRowSpacing: 1.28,
  racingGridSurfaceClearance: 0.018,
  racingGridStaggerZ: 0,
  slotFillMode: 'two-column-racing-grid-left-right-staggered',
};

export const TOY_PARK_SOLID_BACKGROUND = {
  color: '#f3eadb',
  label: 'solid-warm-cream-background',
};

export const TOY_PARK_SOFT_GUIDE_PHYSICS = {
  enabled: true,
  mode: 'soft-guide-physics',
  hardSplineLock: false,
  collisionPreserved: true,
  launchForwardVelocityRatio: 0.32,
  launchForwardVelocityMin: 3.2,
  competitive: {
    enabled: true,
    launchVarianceRatio: 0.02,
    rearRowLaunchBoostRatio: 0,
    rearRowLaunchBoostMax: 0,
    railSlowdownStartsAtOffsetRatio: 0.72,
    railSlowdownStrength: 0.14,
    railSlowdownMaxDeltaPerFrame: 0.025,
    curveInsideBoostRatio: 0.02,
    curveOutsideSlowdownRatio: 0.04,
    innerCornerRailRescueStartsAtOffsetRatio: 0.58,
    innerCornerRailRescueCenterForceScale: 1.1,
    innerCornerRailRescueTangentForceScale: 0.7,
    offsetFreedomCenterPullReduction: 0.18,
    label: 'Toy Park competitive pass: slight deterministic launch differences, rear-row draft boost, rail slowdown, and curve inside/outside lane risk-reward without changing classic physics',
  },
  startForwardSustainSeconds: 1.25,
  startForwardVelocityRatio: 0.42,
  startForwardVelocityMin: 3.6,
  startForwardMaxDeltaPerFrame: 0.18,
  forwardAssist: 1.185,
  centerPull: 0.435,
  curveAssist: 0.69,
  bendTangentAssist: 0.21,
  maxGuideForce: 5.55,
  maxCombinedGuideForce: 6.9,
  lateralFreedom: 0.78,
  minForwardSpeedRatio: 0.42,
  sustainForwardSpeedRatio: 0.38,
  fullSpeedRecoveryRatio: 0.9,
  fullSpeedRecoveryForceScale: 0.345,
  fullSpeedRecoveryMaxForce: 3.15,
  fullSpeedRecoveryGapStartRatio: 0.12,
  fullSpeedRecoveryGapFullRatio: 0.72,
  fullSpeedRecoveryCurveScale: 0.28,
  fullSpeedRecoveryRailScale: 0.22,
  sustainVelocityBlend: 0.14,
  centerPullStartsAtOffsetRatio: 0.16,
  curveStartsAtDegrees: 12,
  lookAhead: 0.95,
  label: 'Toy Park soft guide physics: Cannon sphere collisions remain; every marble gets a scoped forward launch plus capped tangent sustain and gentle centre pull, no spline lock',
};

export const TOY_PARK_MARBLE_VISUAL_THEME = {
  key: 'toyPark',
  label: 'Toy Park',
  description: 'Playroom-style toy colors for testing the pendulum-hammer mechanic preview.',
  colorLabels: ['Rose Candy', 'Cotton Candy Split', 'Aqua Neon', 'Amber Spark', 'Lime Comet', 'Pearl White'],
  patternKeys: ['checker', 'speckle', 'ripple', 'rings', 'chevron'],
  materialOverride: 'candy',
};

export const TOY_PARK_WORLD_VISUAL_THEME_STYLE = {
  track: { base: '#aab4b9', mid: '#c4cdd1', accent: '#c73535', secondary: '#f1eadf', line: '#df8b36', pattern: 'soft-clay-road-panels', roughness: 0.9, metalness: 0.0, clearcoat: 0.08, clayGrain: 'heavy-pitted-molded-plastic' },
  ground: { base: '#efe2c4', mid: '#c7f9cc', accent: '#ffd34e', secondary: '#4fc96a', pattern: 'foam-mat-stars', roughness: 0.86, metalness: 0.0 },
  rail: { base: '#cc2f34', mid: '#f0e7d9', accent: '#fffaf0', secondary: '#8a7f79', pattern: 'red-white-heavy-clay-curb', roughness: 0.82, metalness: 0.0, clearcoat: 0.12, clayGrain: 'heavy-pitted-molded-plastic' },
  gate: { base: '#3b2b55', panel: '#d83a3a', warning: '#ffd34e', emissive: '#28133f', signEmissive: '#4a2a00' },
};

export function buildToyParkPhysicsMechanicProfile(noRollingSlowdown) {
  return {
    key: 'toyPark',
    label: 'Toy Park — flat clay playset preview',
    renderSafeDefault: false,
    isolatedPreviewOnly: true,
    worldGravityY: -16,
    speedScale: 1.08,
    accelScale: 1.02,
    startImpulseScale: 0,
    maxSpeedScale: 0.72,
    unstuckScale: 0,
    marbleMassScale: 0.92,
    marbleRadiusScale: 1.0,
    linearDamping: 0.18,
    angularDamping: 0.22,
    maxAngularSpeed: 18,
    trackContact: { friction: 0, restitution: 0.08 },
    marbleContact: { friction: 0.08, restitution: 0.34 },
    obstacleContact: { friction: 0.12, restitution: 0.42 },
    slopeDriveOverrides: {
      enabled: true,
      model: 'toy-park-soft-guide-tangent-drive',
      dropPerMeter: 0,
      minSegmentDropPerMeter: 0,
      undulationAmplitude: 0,
      forwardGravityScale: 0,
      assistForceRatio: TOY_PARK_SOFT_GUIDE_PHYSICS.forwardAssist,
      guidePointBias: 0.42,
      guidePointBiasMin: 0,
      guidePointBiasMax: 0.7,
      preserveSpeedAssists: false,
      lookAhead: TOY_PARK_SOFT_GUIDE_PHYSICS.lookAhead,
      maxSpeedRatio: 1.23,
      forecastBehindTolerance: 0.04,
      forceGapMin: 0.14,
      forceGapMax: 0.82,
      backwardDamping: 1,
      lateralDamping: 1,
      capHorizontalSpeed: true,
      label: 'Toy Park opt-in soft guide: flat track has no downhill slope; capped tangent drive keeps balls moving while preserving free physics and collisions',
    },
    softGuidePhysics: TOY_PARK_SOFT_GUIDE_PHYSICS,
    contactLabel: 'Toy Park opt-in physics: flat clay/plastic playset contact feel, isolated behind /toypark or physicsMechanic=toyPark',
  };
}
