export const TOY_PARK_TRACK_WIDTH_SCALE = 0.42;

export const TOY_PARK_TILE_RENDER_STATUS = {
  renderReady: 'render-ready',
  draft: 'draft-upcoming',
  cancelled: 'cancelled',
};

export const TOY_PARK_TRACK_TILE_LIBRARY = {
  start: {
    key: 'toy-park-start-board',
    label: '開始板塊',
    role: 'start',
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.renderReady,
    status: 'existing-flat-start-board-module',
  },
  straight: {
    key: 'toy-park-straight-road-tile',
    label: '直路板塊',
    role: 'straight',
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.renderReady,
    length: 14,
    prototypeLoopLength: 7,
    turnDegrees: 0,
    surfaceMarker: 'soft-blue-center-inset',
  },
  candyPopStraightObstacle: {
    key: 'toy-park-candy-pop-straight-obstacle-tile',
    label: 'Candy Pop直線障礙物板塊',
    role: 'straight-obstacle',
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.renderReady,
    length: 14,
    prototypeLoopLength: 7,
    turnDegrees: 0,
    surfaceMarker: 'pink-orange-candy-pop-bumper-lane',
    obstaclePattern: 'alternating-left-right-candy-pop-bumpers',
    obstacleSizing: 'bumper-diameter-about-2.5x-marble-diameter',
    interfaceWidthPolicy: 'same-track-width-and-rail-opening-as-other-toy-park-road-tiles',
  },
  windmillSpinnerCircle: {
    key: 'toy-park-windmill-spinner-circle-tile',
    label: 'Toy Windmill Spinner圓形板塊',
    role: 'circle-obstacle',
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.renderReady,
    length: 6.3,
    prototypeLoopLength: 6.3,
    turnDegrees: 0,
    surfaceMarker: 'light-purple-circular-windmill-spinner',
    diameterScaleVsStandardRoadWidth: 1.95,
    connectorWidthPolicy: 'same-track-width-and-open-rail-opening-as-other-toy-park-road-tiles',
    obstaclePattern: 'center-four-blade-rotating-windmill-spinner',
    railAndTrackColor: 'light-purple',
  },
  mintSpikeBend45Draft: {
    key: 'toy-park-mint-spike-45-bend-draft-tile',
    label: 'Mint Chocolate Spike 45°彎位板塊',
    role: 'bend-obstacle',
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.renderReady,
    length: 16,
    prototypeLoopLength: 16,
    turnDegrees: 45,
    defaultTurnDegrees: 45,
    surfaceMarker: 'mint-green-45-degree-bend-with-chocolate-pop-up-cone-spikes',
    railAndTrackColor: 'mint-green',
    obstaclePattern: 'marble-sized-chocolate-cone-spikes-pop-up-one-second-down-next-second',
    obstacleSizing: 'cone-base-about-one-marble-diameter',
    interfaceWidthPolicy: 'same-track-width-and-rail-opening-as-other-toy-park-road-tiles',
    formalizedReason: 'user-approved-render-ready-spike-tile-set',
  },
  rampUp: {
    key: 'toy-park-ramp-up-road-tile',
    label: '上斜橋板塊（已取消）',
    role: 'disabled-ramp-up',
    length: 6.5,
    turnDegrees: 0,
    elevationRole: null,
    bridgeHeight: 0,
    surfaceMarker: null,
    disabled: true,
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.cancelled,
    status: 'cancelled-by-user-request-generator-uses-road-footprint-avoidance-instead-of-ramp-bridge',
  },
  elevatedStraight: {
    key: 'toy-park-elevated-straight-road-tile',
    label: '高架直路板塊（已取消）',
    role: 'disabled-elevated-straight',
    length: 7,
    turnDegrees: 0,
    elevationRole: null,
    bridgeHeight: 0,
    surfaceMarker: null,
    disabled: true,
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.cancelled,
    status: 'cancelled-by-user-request-generator-uses-road-footprint-avoidance-instead-of-elevated-bridge',
  },
  rampDown: {
    key: 'toy-park-ramp-down-road-tile',
    label: '落斜橋板塊（已取消）',
    role: 'disabled-ramp-down',
    length: 6.5,
    turnDegrees: 0,
    elevationRole: null,
    bridgeHeight: 0,
    surfaceMarker: null,
    disabled: true,
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.cancelled,
    status: 'cancelled-by-user-request-generator-uses-road-footprint-avoidance-instead-of-ramp-bridge',
  },
  variableBend: {
    key: 'toy-park-variable-angle-bend-tile',
    label: '可變角度彎位板塊',
    role: 'corner',
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.renderReady,
    length: 11,
    prototypeLoopLength: 4,
    defaultTurnDegrees: 60,
    minTurnDegrees: 15,
    maxTurnDegrees: 120,
    angleVariable: true,
    surfaceMarker: 'warm-yellow-variable-bend-inset',
  },
  disabledUTurn180: {
    key: 'toy-park-180-degree-u-turn-tile',
    label: '180度U-turn板塊（已取消）',
    role: 'disabled-u-turn',
    disabled: true,
    turnDegrees: 180,
    status: 'cancelled-by-user-request-u-turn-tile-looked-strange',
  },
  disabledCorner45: {
    key: 'toy-park-45-degree-bend-tile',
    label: '45度彎位板塊（已取消）',
    role: 'disabled-corner',
    disabled: true,
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.cancelled,
    replacedBy: ['toy-park-variable-angle-bend-tile'],
    status: 'cancelled-by-user-request',
  },
  finish: {
    key: 'toy-park-finish-board',
    label: '終點板塊',
    role: 'finish',
    renderStatus: TOY_PARK_TILE_RENDER_STATUS.renderReady,
    length: 4.8,
    status: 'new-flat-finish-board-module',
  },
};

export const isToyParkTileRenderReady = (tile) => Boolean(tile)
  && tile.disabled !== true
  && tile.renderStatus === TOY_PARK_TILE_RENDER_STATUS.renderReady;

export const getToyParkRenderReadyTrackTiles = () => Object.fromEntries(
  Object.entries(TOY_PARK_TRACK_TILE_LIBRARY).filter(([, tile]) => isToyParkTileRenderReady(tile))
);

export const getToyParkDraftTrackTiles = () => Object.fromEntries(
  Object.entries(TOY_PARK_TRACK_TILE_LIBRARY).filter(([, tile]) => tile?.renderStatus === TOY_PARK_TILE_RENDER_STATUS.draft)
);

export const TOY_PARK_START_GATE_OVERRIDES = {
  style: 'track-aligned-gravity-staging-chute-with-optional-toy-park-racing-grid-start',
  gateEnabled: true,
  toyParkGateEnabled: false,
  racingGridStartEnabled: true,
  racingGridColumns: 4,
  racingGridOccupiedPerRow: 2,
  racingGridRows: 4,
  racingGridColumnSpacing: 2.34,
  racingGridRowSpacing: 1.28,
  racingGridSurfaceClearance: 0.018,
  racingGridStaggerZ: 0,
  slotFillMode: 'two-column-racing-grid-left-right-staggered',
};

export const TOY_PARK_SOLID_BACKGROUND = {
  color: '#f7e8c8',
  label: 'solid-vanilla-cream-background',
};

export const TOY_PARK_SOFT_GUIDE_PHYSICS = {
  enabled: true,
  mode: 'soft-guide-physics',
  hardSplineLock: false,
  collisionPreserved: true,
  launchForwardVelocityRatio: 0.32,
  launchForwardVelocityMin: 3.2,
  competitive: {
    enabled: true,
    launchVarianceRatio: 0.02,
    rearRowLaunchBoostRatio: 0,
    rearRowLaunchBoostMax: 0,
    railSlowdownStartsAtOffsetRatio: 0.72,
    railSlowdownStrength: 0.14,
    railSlowdownMaxDeltaPerFrame: 0.025,
    curveInsideBoostRatio: 0.02,
    curveOutsideSlowdownRatio: 0.04,
    innerCornerRailRescueStartsAtOffsetRatio: 0.58,
    innerCornerRailRescueCenterForceScale: 1.1,
    innerCornerRailRescueTangentForceScale: 0.7,
    offsetFreedomCenterPullReduction: 0.18,
    label: 'Toy Park competitive pass: slight deterministic launch differences, rear-row draft boost, rail slowdown, and curve inside/outside lane risk-reward without changing classic physics',
  },
  startForwardSustainSeconds: 1.25,
  startForwardVelocityRatio: 0.34,
  startForwardVelocityMin: 2.88,
  startForwardMaxDeltaPerFrame: 0.144,
  forwardAssist: 0.948,
  centerPull: 0.348,
  curveAssist: 0.552,
  bendTangentAssist: 0.168,
  maxGuideForce: 4.44,
  maxCombinedGuideForce: 5.52,
  lateralFreedom: 0.78,
  minForwardSpeedRatio: 0.42,
  sustainForwardSpeedRatio: 0.38,
  fullSpeedRecoveryRatio: 0.9,
  fullSpeedRecoveryForceScale: 0.345,
  fullSpeedRecoveryMaxForce: 3.15,
  fullSpeedRecoveryGapStartRatio: 0.12,
  fullSpeedRecoveryGapFullRatio: 0.72,
  fullSpeedRecoveryCurveScale: 0.28,
  fullSpeedRecoveryRailScale: 0.22,
  sustainVelocityBlend: 0.14,
  centerPullStartsAtOffsetRatio: 0.16,
  curveStartsAtDegrees: 12,
  lookAhead: 0.95,
  label: 'Toy Park soft guide physics: Cannon sphere collisions remain; every marble gets a scoped forward launch plus capped tangent sustain and gentle centre pull, no spline lock',
};

export const TOY_PARK_MARBLE_VISUAL_THEME = {
  key: 'toyPark',
  label: 'Toy Park',
  description: 'Playroom-style toy colors for testing the pendulum-hammer mechanic preview.',
  colorLabels: [
    'Candy Captain Red',
    'Bubble Goblin Mint',
    'Rocket Bunny Blue',
    'Choco Bear Brown',
    'Neon Penguin Black',
    'Rainbow Unicorn Pearl',
    'Mecha Duck Yellow',
    'Lava Dragon Orange',
  ],
  patternKeys: ['candy-captain', 'bubble-goblin', 'rocket-bunny', 'choco-bear', 'neon-penguin', 'rainbow-unicorn', 'mecha-duck', 'lava-dragon'],
  materialOverride: 'candy',
};

export const TOY_PARK_MARBLE_IDENTITIES = [
  {
    name: 'Candy Captain',
    colorLabel: 'Candy Captain Red',
    hex: '#ff3b5c',
    color: 0xff3b5c,
    palette: ['#ff3b5c', '#fff3d6', '#ffd84a', '#ffffff'],
    patternKey: 'candy-captain',
    patternName: 'Captain Candy Face',
    materialKey: 'candy',
    icon: 'captain-hat-smile',
    tagline: 'Red-white candy swirl with a tiny captain hat smile.',
  },
  {
    name: 'Bubble Goblin',
    colorLabel: 'Bubble Goblin Mint',
    hex: '#46e6a6',
    color: 0x46e6a6,
    palette: ['#46e6a6', '#35c7ff', '#c77dff', '#f8ffff'],
    patternKey: 'bubble-goblin',
    patternName: 'Bubble Goblin Eyes',
    materialKey: 'candy',
    icon: 'goblin-eyes-bubbles',
    tagline: 'Mint-blue bubble glass with cheeky goblin eyes.',
  },
  {
    name: 'Rocket Bunny',
    colorLabel: 'Rocket Bunny Blue',
    hex: '#2f80ff',
    color: 0x2f80ff,
    palette: ['#2f80ff', '#ffe45e', '#ffffff', '#ff7a3d'],
    patternKey: 'rocket-bunny',
    patternName: 'Rocket Bunny Stars',
    materialKey: 'candy',
    icon: 'bunny-rocket-stars',
    tagline: 'Bright blue starfield with a white bunny rocket decal.',
  },
  {
    name: 'Choco Bear',
    colorLabel: 'Choco Bear Brown',
    hex: '#7a3e22',
    color: 0x7a3e22,
    palette: ['#7a3e22', '#f29a3f', '#ffe8b5', '#3b1b0f'],
    patternKey: 'choco-bear',
    patternName: 'Caramel Bear Face',
    materialKey: 'candy',
    icon: 'bear-face-caramel',
    tagline: 'Glossy chocolate with caramel drips and a round bear face.',
  },
  {
    name: 'Neon Penguin',
    colorLabel: 'Neon Penguin Black',
    hex: '#111827',
    color: 0x111827,
    palette: ['#111827', '#00f5ff', '#ff4fd8', '#ffffff'],
    patternKey: 'neon-penguin',
    patternName: 'Neon Penguin Shades',
    materialKey: 'neon',
    icon: 'penguin-sunglasses',
    tagline: 'Black neon circuits with a cool penguin shades face.',
  },
  {
    name: 'Rainbow Sprinkles',
    colorLabel: 'Rainbow Unicorn Pearl',
    hex: '#f8f7ff',
    color: 0xf8f7ff,
    palette: ['#f8f7ff', '#ff7ac8', '#9b5cff', '#4de3ff', '#ffe66d'],
    patternKey: 'rainbow-unicorn',
    patternName: 'Unicorn Sprinkle Wink',
    materialKey: 'pearl',
    icon: 'unicorn-horn-wink',
    tagline: 'Pearl white rainbow sprinkles with a unicorn horn wink.',
  },
  {
    name: 'Mecha Duck',
    colorLabel: 'Mecha Duck Yellow',
    hex: '#ffd21f',
    color: 0xffd21f,
    palette: ['#ffd21f', '#8b95a1', '#ff8a00', '#fff7b8'],
    patternKey: 'mecha-duck',
    patternName: 'Robot Duck Beak',
    materialKey: 'candy',
    icon: 'duck-beak-robot-eye',
    tagline: 'Toy yellow duck with silver panels and one robot eye.',
  },
  {
    name: 'Lava Dragon',
    colorLabel: 'Lava Dragon Orange',
    hex: '#ff4a1c',
    color: 0xff4a1c,
    palette: ['#ff4a1c', '#2b193d', '#ffd000', '#7a1000'],
    patternKey: 'lava-dragon',
    patternName: 'Lava Dragon Eye',
    materialKey: 'candy',
    icon: 'dragon-eye-horns',
    tagline: 'Orange lava cracks with a tiny dragon eye and horns.',
  },
];

export const TOY_PARK_WORLD_VISUAL_THEME_STYLE = {
  track: { base: '#aab4b9', mid: '#c4cdd1', accent: '#c73535', secondary: '#f1eadf', line: '#df8b36', pattern: 'soft-clay-road-panels', roughness: 0.9, metalness: 0.0, clearcoat: 0.08, clayGrain: 'heavy-pitted-molded-plastic' },
  ground: { base: '#efe2c4', mid: '#c7f9cc', accent: '#ffd34e', secondary: '#4fc96a', pattern: 'foam-mat-stars', roughness: 0.86, metalness: 0.0 },
  rail: { base: '#cc2f34', mid: '#f0e7d9', accent: '#fffaf0', secondary: '#8a7f79', pattern: 'red-white-heavy-clay-curb', roughness: 0.82, metalness: 0.0, clearcoat: 0.12, clayGrain: 'heavy-pitted-molded-plastic' },
  gate: { base: '#3b2b55', panel: '#d83a3a', warning: '#ffd34e', emissive: '#28133f', signEmissive: '#4a2a00' },
};

export function buildToyParkPhysicsMechanicProfile(noRollingSlowdown) {
  return {
    key: 'toyPark',
    label: 'Toy Park — flat clay playset preview',
    renderSafeDefault: false,
    isolatedPreviewOnly: true,
    worldGravityY: -16,
    speedScale: 1.3478,
    accelScale: 1.273,
    startImpulseScale: 0,
    maxSpeedScale: 0.8986,
    unstuckScale: 0,
    marbleMassScale: 0.92,
    marbleRadiusScale: 1.0,
    linearDamping: 0.18,
    angularDamping: 0.22,
    maxAngularSpeed: 18,
    trackContact: { friction: 0, restitution: 0.08 },
    marbleContact: { friction: 0.08, restitution: 0.34 },
    obstacleContact: { friction: 0.12, restitution: 0.42 },
    slopeDriveOverrides: {
      enabled: true,
      model: 'toy-park-soft-guide-tangent-drive',
      dropPerMeter: 0,
      minSegmentDropPerMeter: 0,
      undulationAmplitude: 0,
      forwardGravityScale: 0,
      assistForceRatio: TOY_PARK_SOFT_GUIDE_PHYSICS.forwardAssist,
      guidePointBias: 0.42,
      guidePointBiasMin: 0,
      guidePointBiasMax: 0.7,
      preserveSpeedAssists: false,
      lookAhead: TOY_PARK_SOFT_GUIDE_PHYSICS.lookAhead,
      maxSpeedRatio: 1.23,
      forecastBehindTolerance: 0.04,
      forceGapMin: 0.14,
      forceGapMax: 0.82,
      backwardDamping: 1,
      lateralDamping: 1,
      capHorizontalSpeed: true,
      label: 'Toy Park opt-in soft guide: flat track has no downhill slope; capped tangent drive keeps balls moving while preserving free physics and collisions',
    },
    softGuidePhysics: TOY_PARK_SOFT_GUIDE_PHYSICS,
    contactLabel: 'Toy Park opt-in physics: flat clay/plastic playset contact feel, isolated behind /toypark or physicsMechanic=toyPark',
  };
}
