import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const js = readFileSync(new URL('../src/main.js', import.meta.url), 'utf8');
const css = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');

assert.match(html, /id="ui-toggle-btn"/, 'index.html should include a left UI hide/show toggle button');
assert.match(html, /id="record-btn"/, 'index.html should include a video recording toggle button');
assert.match(html, /id="record-status"/, 'index.html should include recording status text');
assert.match(js, /toggleLeftUI\(/, 'main.js should implement toggleLeftUI');
assert.match(js, /toggleRecording\(/, 'main.js should implement toggleRecording');
assert.match(js, /MediaRecorder/, 'main.js should use MediaRecorder for canvas video capture');
assert.match(js, /getDisplayMedia/, 'main.js should support full-page/screen recording so the right UI can be captured');
assert.match(js, /preferScreenRecording/, 'main.js should default to screen recording when available');
assert.match(css, /\.hud-left\.collapsed/, 'styles.css should style the collapsed left HUD state');
assert.match(css, /\.ui-toggle/, 'styles.css should style the UI toggle button');
assert.match(css, /\.recording/, 'styles.css should style recording state');

assert.match(html, /id="obstacle-slider"/, 'index.html should include obstacle density slider');
assert.match(html, /id="curve-select"/, 'index.html should include curve style selector');
assert.match(js, /const SPEED_SCALE = 4/, 'main.js should double the overall speed scale');
assert.match(js, /OBSTACLE_PRESETS/, 'main.js should define obstacle density presets');
assert.match(js, /CURVE_PRESETS/, 'main.js should define curve style presets');
assert.match(js, /updateObstaclePreset\(/, 'main.js should implement obstacle density UI handling');
assert.match(js, /this\.ui\.curveSelect/, 'main.js should wire the curve style selector');
assert.match(js, /curveStyle/, 'main.js debug/state should expose curve style');

assert.match(html, /id="controls-toggle-btn"/, 'index.html should include independent controls panel hide button');
assert.match(html, /id="camera-toggle-btn"/, 'index.html should include independent camera panel hide button');
assert.match(html, /class="panel action-panel"/, 'index.html should split start/pause/record into an action panel group');
assert.match(js, /togglePanel\(/, 'main.js should implement independent panel hide/show');
assert.match(js, /createWoodTexture\(/, 'main.js should create a wood texture for the game background');
assert.match(js, /backgroundMaterial: 'wood'/, 'main.js debug should expose wood background material');
assert.match(css, /\.panel-header/, 'styles.css should style panel headers with hide buttons');
assert.match(css, /\.action-panel/, 'styles.css should style the action button group');
assert.match(css, /\.panel\.collapsed/, 'styles.css should collapse individual panels');

assert.match(js, /enableAllCameraMouseOrbit/, 'main.js should keep mouse orbit controls enabled for every camera mode');
assert.match(js, /getMouseOrbitAdjustedCamera\(/, 'main.js should apply mouse orbit offset to assisted cameras');
assert.match(js, /controls\.enabled = true/, 'OrbitControls should be enabled outside orbit mode too');
assert.match(js, /railSpring/, 'main.js should expose a gentle rail rebound/spring setting');
assert.match(js, /RAIL_REBOUND/, 'main.js should define rail rebound contact physics');
assert.match(js, /createTrackTexture\(/, 'main.js should add track surface material texture');
assert.match(js, /createRailTexture\(/, 'main.js should add rail material texture');
assert.match(js, /trackMaterials/, 'main.js debug should expose added track materials');

assert.match(html, /id="catchup-toggle"/, 'index.html should include catch-up assist option');
assert.match(html, /checked/, 'catch-up assist should default to enabled');
assert.match(js, /CATCHUP_ASSIST/, 'main.js should define restrained catch-up assist settings');
assert.match(js, /updateCatchupAssist\(/, 'main.js should wire catch-up assist UI');
assert.match(js, /getLeaderId\(/, 'main.js should identify the current leader for catch-up assist');
assert.match(js, /catchupMaxSpeed/, 'main.js should expose catch-up max speed debug info');
assert.match(js, /Seamless.*track/, 'main.js should describe seamless track material');
assert.doesNotMatch(js, /texture\.repeat\.set\(1\.2, 14\)/, 'track texture should not tile into obvious grid blocks');

assert.match(js, /PINBALL_OBSTACLE_TYPES/, 'main.js should define a pinball-style obstacle type list');
assert.match(js, /popBumper/, 'pinball obstacles should include pop bumpers');
assert.match(js, /slingshot/, 'pinball obstacles should include slingshot bumpers');
assert.doesNotMatch(js, /'jumpRamp'/, 'pinball obstacle type list should no longer include jump ramps');
assert.doesNotMatch(js, /createCurveRailObstacle\(/, 'main.js should remove slanted/curved rail replacement obstacles');
assert.doesNotMatch(js, /curveRail/, 'main.js should no longer generate curveRail obstacle bumpers');
assert.match(js, /spinnerGate/, 'pinball obstacles should include spinner gates');
assert.match(js, /rolloverLane/, 'pinball obstacles should include rollover lanes');
assert.match(js, /dropTarget/, 'pinball obstacles should include drop targets');
assert.match(js, /createPinballObstacle\(/, 'main.js should route obstacle creation through pinball-style obstacle builders');
assert.doesNotMatch(js, /createJumpRampObstacle\(/, 'main.js should remove jump ramp obstacle implementation');
assert.match(js, /obstacleTypeCounts/, 'debug state should expose counts for the six pinball obstacle types');
assert.match(js, /pinballObstacleTypes/, 'debug state should expose the active pinball obstacle type list');
assert.match(js, /pinballObstacles/, 'main.js should keep interactive pinball obstacle records');
assert.match(js, /updatePinballObstacles\(/, 'main.js should update active pinball obstacles every frame');
assert.match(js, /applyPopBumperImpulse\(/, 'pop bumpers should actively apply a bounce impulse');
assert.match(js, /applySlingshotImpulse\(/, 'slingshots should actively kick marbles sideways like pinball slingshots');
assert.match(js, /replacementObstacleDesigns: \[\]/, 'debug state should show no replacement rail obstacles after removing slanted/curved rails');
assert.match(js, /applySpinnerGateImpulse\(/, 'spinner gates should actively apply a rotating tangential impulse');
assert.match(js, /applyRolloverLaneBoost\(/, 'rollover lanes should actively boost marbles and count interactions');
assert.match(js, /applyDropTargetHit\(/, 'drop targets should knock down and remove their blocking bodies when hit');
assert.match(js, /hairpinTurnCount/, 'debug state should expose generated hairpin turn count');
assert.match(js, /hairpinTurns/, 'debug state should expose generated hairpin turn metadata');
assert.match(js, /trackPieceSystem = 'modular-pieces'/, 'main.js should switch track generation to modular pieces');
assert.match(js, /modularTrackPieces/, 'debug state should expose modular track pieces');
assert.match(js, /corner-45/, 'modular track generation should include 45-degree corner pieces');
assert.match(js, /corner-90/, 'modular track generation should include 90-degree corner pieces');
assert.match(js, /90 \* dir/, '90-degree modular corner pieces should explicitly turn 90 degrees');
assert.match(js, /THREE\.MathUtils\.degToRad\(turnDegrees\)/, 'track pieces should convert turn degrees into heading radians');
assert.match(js, /modularTrackPieceCounts/, 'debug state should expose straight/45/90 track piece counts');
assert.match(js, /rightAngleTurnCount/, 'debug state should expose visible 90-degree corner count');
assert.match(js, /rightAngleTurns/, 'debug state should expose generated 90-degree corner metadata');
assert.match(js, /90-degree right-angle corners/, 'track debug should describe visible 90-degree right-angle corner style');
assert.match(js, /FALL_TIME_PENALTY_SECONDS = 2/, 'falling off track should add a two-second time penalty');
assert.match(js, /applyFallTimePenalty\(/, 'main.js should implement fall time penalties');
assert.match(js, /finishTime = this\.elapsed \+ \(data\.timePenalty \|\| 0\)/, 'finish times should include accumulated fall penalties');
assert.match(js, /fallPenalty/, 'debug state should expose fall penalty totals');
assert.match(js, /spinnerSpeed/, 'spinner gates should have a visual spin speed');
assert.match(js, /createPinballPlayfieldTexture\(/, 'track should use pinball playfield art texture');
assert.match(js, /createNeonRubberTexture\(/, 'rails should use neon rubber pinball material texture');
assert.match(js, /MeshPhysicalMaterial/, 'pinball obstacles should use glossy physical plastic materials');
assert.match(js, /pinballMaterialStyle/, 'debug state should expose the pinball material style');
assert.match(js, /finishPodiumStyle/, 'debug state should expose podium finish style');
assert.match(js, /top-3-on-podium-rest-below/, 'finish collector should place top 3 on podium and remaining finishers below');
assert.match(js, /podiumSlots/, 'podium collector should define top-three podium slots');
assert.match(js, /lowerFinisherSlots/, 'podium collector should expose lower finisher slots for non-top-three marbles');
assert.match(js, /PODIUM_COLLECTOR/, 'finish collector should identify itself as a podium collector');

assert.match(html, /data-camera="default"/, 'index.html should add a default auto camera mode button');
assert.match(js, /defaultCameraMode: 'default'/, 'debug state should expose default auto camera mode');
assert.match(js, /getDefaultCameraMode\(/, 'main.js should choose default camera shots automatically');
assert.match(js, /defaultCameraSequence/, 'debug state should expose default camera sequence');
assert.match(js, /unfinishedOrder/, 'default camera should track unfinished marbles in remaining-order after finish view');
assert.match(js, /podium360/, 'default camera should orbit the podium 360 after all finishers arrive');
assert.match(js, /leadPackCloseCamera/, 'debug state should expose closer lead-pack camera tuning');

assert.match(html, /Short 240m/, 'short track preset should be doubled to 240m');
assert.match(html, /Standard 380m/, 'standard track preset should be doubled to 380m');
assert.match(html, /Long 560m/, 'long track preset should be doubled to 560m');
assert.match(html, /Endurance 840m/, 'endurance track preset should be doubled to 840m');
assert.match(html, /id="custom-length-input"/, 'index.html should support typed custom track length');
assert.match(js, /getCustomTrackLength\(/, 'main.js should read and clamp typed custom track length');
assert.match(js, /customTrackLength/, 'debug state should expose the custom track length');
assert.match(js, /railMomentumAssist/, 'main.js should add rail momentum assist to preserve forward inertia after rail scrapes');
assert.match(js, /optimized-dense-overlapped-smooth/, 'main.js should use optimized dense overlapped guardrail joins');
assert.match(js, /optimizedRailBodies/, 'debug track stats should expose optimized guardrail body count');
assert.match(js, /performanceProfile/, 'debug state should expose performance profile throttles');
assert.match(js, /performanceOptimizations/, 'debug state should list applied performance optimizations');
assert.match(js, /rankingCacheMs/, 'ranking sorts should be cached briefly for per-frame performance');
assert.match(js, /applyRailMomentumAssist\(/, 'main.js should apply anti-stall rail momentum assist during drive');
assert.match(js, /birdEyeCameraAngle/, 'debug state should expose the more bird-eye camera angle');
assert.match(js, /closer-to-bird-eye overhead follow/, 'debug state should describe the overhead camera style');
assert.match(js, /MARBLE_COLOR_STYLES/, 'main.js should define reusable marble color identities');
assert.match(js, /MARBLE_PATTERN_STYLES/, 'main.js should define reusable marble pattern identities');
assert.match(js, /MARBLE_SIZE_STYLES/, 'main.js should define reusable marble size identities');
assert.match(js, /createMarbleIdentity\(/, 'main.js should create unique reusable marble codes');
assert.match(js, /marbleIdentitySystem: 'reusable-code-name-color-pattern-size'/, 'debug state should expose the reusable identity system');
assert.match(js, /reusableMarbleRegistry/, 'debug state should expose a reusable marble registry');
assert.match(js, /reusableRaceResults/, 'debug state should expose post-race reusable result lines');
assert.match(js, /MB-##-RGB-PAT-SIZE/, 'debug state should document the marble code format');
assert.match(js, /copyReusableMarble\(/, 'main.js should copy one reusable marble identity from the leaderboard');
assert.match(js, /navigator\.clipboard\?\.writeText/, 'copy button should use the Clipboard API when available');
assert.match(js, /class="copy-marble-btn"/, 'leaderboard rows should show a copy button beside the racer name');
assert.doesNotMatch(js, /<span class="racer-code">/, 'leaderboard overlay should not show marble codes directly');
assert.match(css, /\.copy-marble-btn/, 'leaderboard copy button should be styled');
assert.doesNotMatch(css, /\.racer-code/, 'hidden overlay code styling should be removed');

console.log('static feature checks passed');

